import { RectangleSvgIcons } from "../Components/AllSvgIcons";

let dashboardData = [
  {
    id: 1,
    pic:"case01.jpg",
    name: "stylish-summer-necklace",
    images: 3,
    status: "Active",
    stock: "0 in stock for 50 variants",
    progress: "Not Generated",
  },
  {
    id: 2,
    pic:"armChair.jpg",
    name: "threader-necklace-closeup",
    images: 5,
    status: "Active",
    stock: "360 in stock",
    progress: "In Progress",
  },
  {
    id: 3,
    pic:"bed01.jpg",
    name: "silver-threader-necklace",
    images: 2,
    status: "Draft",
    stock: "120 in stock",
    progress: "Not Generated",
  },
  {
    id: 4,
    pic:"bed02.jpg",
    name: "silver-threader-necklace",
    images: 2,
    status: "Active",
    stock: "120 in stock",
    progress: "Completed",
  },
  {
    id: 5,
    pic:"chair01.jpg",
    name: "threader-necklace-closeup",
    images: 2,
    status: "Active",
    stock: "120 in stock",
    progress: "Completed",
  },
  {
    id: 6,
    pic:"chair02.jpg",
    name: "silver-threader-necklace",
    images: 2,
    status: "Active",
    stock: "120 in stock",
    progress: "Completed",
  },
  {
    id: 7,
    pic:"chair03.jpg",
    name: "silver-threader-necklace",
    images: 2,
    status: "Active",
    stock: "120 in stock",
    progress:"Completed",
  },
  {
    id: 8,
    pic:"clock01.jpg",
    name: "silver-threader-necklace",
    images: 2,
    status: "Active",
    stock: "120 in stock",
    progress: "Completed",
  },
  {
    id: 9,
    pic:"table01.jpg",
    name: "threader-necklace-closeup",
    images: 2,
    status: "Active",
    stock: "120 in stock",
    progress: "Completed",

  },
  {
    id: 10,
    pic:"table02.jpg",
    name: "silver-threader-necklace",
    images: 2,
    status: "Active",
    stock: "120 in stock",
    progress: "Completed",
  },
  {
    id: 11,
    pic:"table03.jpg",
    name: "silver-threader-necklace",
    images: 2,
    status: "Active",
    stock: "120 in stock",
    progress: "Completed",
  },
  {
    id: 12,
    pic:"dresser01.jpg",
    name: "silver-threader-necklace",
    images: 2,
    status: "Active",
    stock: "120 in stock",
    progress: "Completed",
  },
];

export default dashboardData;